name: Generate PDF on Commit

on:
  push:
    branches:
      - main

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        run: |
          cd Template  # Move into the correct directory
          latexmk -pdf -interaction=nonstopmode Resume.tex

      - name: Move PDF to Root
        run: mv Template/Resume.pdf Resume.pdf

      - name: Commit and Push PDF if Changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Resume.pdf
          git commit -m "Automated PDF generation"
          git push
