name: Generate PDF on Commit

on:
  push:
    branches:
      - main

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history is available for pushing changes

      - name: Compile LaTeX to PDF
        run: |
          cd Template  # Change directory to where the LaTeX source lives
          latexmk -pdf -interaction=nonstopmode Resume.tex

      - name: Move PDF to Root
        run: mv Template/Resume.pdf Resume.pdf

      - name: Commit and Push PDF if Changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          # Check if Resume.pdf has changes
          if [ -n "$(git status --porcelain Resume.pdf)" ]; then
            git add Resume.pdf
            git commit -m "Automated PDF generation [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
